### ISSUE TITLE
Decide upon, design and develop parsing options that appear after user has entered Commons categories

### ISSUE THREAD

**Issue by trnstlntk** [OpenRefine/CommonsExtension#15]
After a user has entered one or more Commons categories to start an OpenRefine project with, it makes sense to present them with some custom parsing options in the 'Configure Parsing Options' dialog window.

Several that I can think of, which would make sense, from the top of my head:

- Reconcile file names (+ let users specify the language against which they want to reconcile - for possible data extension they may want to do later)
- Display thumbnails of files? y/n
- Display column with Wikitext? y/n
- Display column with categories? y/n
- Display one or more columns with some SDC in it already (user specifies the properties they are interested in)

I may miss some obvious ones, and I can imagine that conversations with potential end users may give us more good ideas/suggestions.

As for building this, the existing Wikitext parsing options in OpenRefine can be used for inspiration (although that interface is not optimal).

In our [March 17 team meeting](https://etherpad.wikimedia.org/p/OpenRefine-SDC-team-meetings) we talked about this a bit. Some of this should be retrievable via API, bypassing the need for the end user to run the Commons reconciliation service, which would be a good thing!

**Comment by trnstlntk** [comment]
As discussed on March 17: no need to put development time in this task yet - let's first prioritize other more crucial bits (eg file upload from disk / from URL). 

IMO it's totally OK for now if we deploy a Commons Extension that bypasses this parsing dialog and presents the user with a bare project with just file names. Unless there are objections or other considerations, which I'd love to hear!

**Comment by trnstlntk** [comment]
Assigning this to @lozanaross (design) and @j-sal (building this dialog; deadline May 31).

**Comment by lozanaross** [comment]
I think in order to be consistent with how other previews work (before project creation) from the above list these are my comments (maybe worth it for @wetneb to have a look at my comments below too):

- _Reconcile file names (+ let users specify the language against which they want to reconcile - for possible data extension they may want to do later)_ >> I think we agree that this should happen automatically, so there is no need to add this as an option
- _Display thumbnails of files? y/n_ >> I think we should indeed include this and allow this also across all other parsing views (also outside the SDC extension)
- _Display column with Wikitext? y/n_ >> I think this is going into data extension territory, so not sure if it is appropriate to include at this stage (handy for users, but not sure if it's not going against the general behaviour of OpenRefine)
- _Display column with categories? y/n_ >> I think this makes sense because it's like giving the source of where each file was retrieved from.
- _Display one or more columns with some SDC in it already (user specifies the properties they are interested in)_ >> I think this is going into data extension territory, so not sure if it is appropriate to include at this stage (handy for users, but not sure if it's not going against the general behaviour of OpenRefine)

In principle, I think we can base this preview on the one generated after users connect to a database for data retrieval (operation seems logically comparable to me). Adding a TO DO for myself here: 

- [ ] to complete the design and add a screenshot to it below.

**Comment by lozanaross** [comment]
I think in order to be consistent with how other previews work (before project creation) from the above list these are my comments (maybe worth it for @wetneb to have a look at my comments below too):

- _Reconcile file names (+ let users specify the language against which they want to reconcile - for possible data extension they may want to do later)_ >> I think we agree that this should happen automatically, so there is no need to add this as an option
- _Display thumbnails of files? y/n_ >> I think we should indeed include this and allow this also across all other parsing views (also outside the SDC extension)
- _Display column with Wikitext? y/n_ >> I think this is going into data extension territory, so not sure if it is appropriate to include at this stage (handy for users, but not sure if it's not going against the general behaviour of OpenRefine)
- _Display column with categories? y/n_ >> I think this makes sense because it's like giving the source of where each file was retrieved from.
- _Display one or more columns with some SDC in it already (user specifies the properties they are interested in)_ >> I think this is going into data extension territory, so not sure if it is appropriate to include at this stage (handy for users, but not sure if it's not going against the general behaviour of OpenRefine)

In principle, I think we can base this preview on the one generated after users connect to a database for data retrieval (operation seems logically comparable to me). Adding a TO DO for myself here: 

- [ ] to complete the design and add a screenshot to it below.

**Comment by lozanaross** [comment]
I've added my suggested design options here: https://xd.adobe.com/view/fdf5a12c-9c30-4449-9eba-d1ea8523dddb-a8a6/ (p. 29)

Happy to discuss changes needed:
![grafik](https://user-images.githubusercontent.com/25489750/167893479-fcc9eefa-fb59-4292-bd64-2f1382de86aa.png)

**Comment by trnstlntk** [comment]
> I've added my suggested design options here: https://xd.adobe.com/view/fdf5a12c-9c30-4449-9eba-d1ea8523dddb-a8a6/ (p. 29)
> 
> Happy to discuss changes needed: ![grafik](https://user-images.githubusercontent.com/25489750/167893479-fcc9eefa-fb59-4292-bd64-2f1382de86aa.png)

Amazing. Thanks!!

I'll provide more detailed feedback in the Adobe document you provided, but for visibility here:

* Display _file_ thumbnails rather than _image_ thumbnails (it's possible that the user will load videos, audio files, etc)
* Include a column with categories: for this option we should explicitly look at what will happen when the user ticks this checkbox. Maybe it's also best to rename this option to 'Include a column with Commons categories' - just for clarity.

In most cases, files have multiple Commons categories. If the user checks the 'Include a column with categories', for me the most obvious outcome would be:
1. The OpenRefine project will then load in record mode (i.e. having multiple lines for each filename)
2. In which each category is in a different cell in a 'Commons category' column
3. And a category is displayed with the category name only, without square brackets or the Category: prefix

For outcome 2, the alternative would be just one cell with a concatenation of categories - not a terrible option, but the record mode approach sounds friendlier to me?

For outcome 3, it could also equally be outputted as [[Category:Historical photos of cats dressed as humans]] or Category:Historical photos of cats dressed as humans - no strong preference here.

Mainly, I think we want to be consistent, also with how the various GREL parsing operations for Wikitext will work, see also [#4823](https://github.com/OpenRefine/OpenRefine/issues/4823).

@j-sal @wetneb any thoughts?

**Comment by lozanaross** [comment]
> I'll provide more detailed feedback in the Adobe document you provided, but for visibility here:

Super thanks!

> - Display file thumbnails rather than image thumbnails (it's possible that the user will load videos, audio files, etc)
Yes, totally.
> - Include a column with categories: for this option we should explicitly look at what will happen when the user ticks this checkbox. Maybe it's also best to rename this option to 'Include a column with Commons categories' - just for clarity.
I don't know if we need Commons, because the checkbox comes underneath the column title "Wikimedia Commons specific options". Although the column titles right now are very far from the checkbox options, so that can be improved, I didn't change yet mostly because if we change here it will have implications to other places in the "Configure parsing options" view, so probably can be changed as part of the overall "audit" of the design system I hope to progress with in the coming months. 

Record mode makes sense I think, users can then always readjust as needed.

**Comment by wetneb** [comment]
It all looks great to me @lozanaross!

> Display one or more columns with some SDC in it already (user specifies the properties they are interested in) >> I think this is going into data extension territory, so not sure if it is appropriate to include at this stage (handy for users, but not sure if it's not going against the general behaviour of OpenRefine)

yes I would rather avoid this - we sort of do this in the wikitable importer and it is not a great user experience because of the additional delay in fetching the data
