### ISSUE TITLE
Release a first version

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/CommonsExtension#81]
People should not have to compile the extension themselves: let them just download it by releasing a first version.

**Comment by trnstlntk** [comment]
I created a draft for the release. Can anyone besides me see this and help me check if I didn't forget anything? @wetneb 👀 ? https://github.com/OpenRefine/CommonsExtension/releases

**Comment by wetneb** [comment]
Looks great!

> This extension will also install the [Wikimedia Commons manifest](https://github.com/OpenRefine/wikibase-manifests/blob/301b57d6cadbf6fddecbfe30b1b5aaa257b8f78a/wikimedia-commons-manifest.json) and the [Wikimedia Commons reconciliation service](https://commonsreconcile.toolforge.org/) by default.

For now that's done by OpenRefine itself already (more precisely the Wikibase extension)… maybe it would make sense to move it here though?

**Comment by trnstlntk** [comment]
@wetneb I hope I did everything right (not the best idea to do it on a Friday evening with a headache). I found the tagging a bit challenging, I did it inside GitHub Desktop [using these instructions](https://docs.github.com/en/desktop/contributing-and-collaborating-using-github-desktop/managing-commits/managing-tags) as I've only used Git on the command line once (a year ago). I tried unzipping the file before adding it to the release and loading it as a proper extension in OpenRefine 3.6.2 and it seems to work fine on my end.

I guess I have two questions that are more related to user-friendliness of naming of things:
* The zipfile is automatically named `openrefine-commons.zip` - can this safely be renamed to a more descriptive filename?
* When unzipped, it unzips as a folder named `module` which I also find vague and not very reassuring. Can this also be renamed somewhere so that it's clearer for the user that they indeed have the Commons extension here?
<img width="584" alt="image" src="https://user-images.githubusercontent.com/9881645/200049253-1872c618-21ee-428a-a706-f898077503a7.png">

**Comment by wetneb** [comment]
> The zipfile is automatically named openrefine-commons.zip - can this safely be renamed to a more descriptive filename?

It can! It would be good to have the version number in there, too.

> When unzipped, it unzips as a folder named module which I also find vague and not very reassuring. Can this also be renamed somewhere so that it's clearer for the user that they indeed have the Commons extension here?

Definitely! I think it can be safely renamed.

Both of those things could be fixed in the build system, so you don't have to do it yourself at every release, so worth opening an issue for it.
